#!/bin/bash
#the genome could download from :
#ftp://hgdownload.cse.ucsc.edu/goldenPath/hg19/chromosomes/

#or using the follow command
GENOMELIST="1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 X Y M"
for  N in $GENOMELIST; do
genomename=chr${N}.fa.gz
rsync -avzp rsync://hgdownload.cse.ucsc.edu/goldenPath/hg19/chromosomes/$genomename .
done

